# Generated by Django 5.2.7 on 2026-01-19 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0002_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="central.company",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="wh_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("storage", "Storage"),
                    ("distribution", "Distribution"),
                    ("production", "Production"),
                    ("returns", "Returns"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
