# Generated by Django 5.2.7 on 2026-01-19 16:33

from django.db import migrations


def assign_default_company(apps, schema_editor):
    """Assign a default company to products that don't have one"""
    Product = apps.get_model('central', 'Product')
    Company = apps.get_model('central', 'Company')
    
    # Get or create a default company
    default_company, created = Company.objects.get_or_create(
        name='Default Company',
        defaults={'status': True}
    )
    
    # Assign the default company to products without a company
    Product.objects.filter(company__isnull=True).update(company=default_company)


def reverse_assign_default_company(apps, schema_editor):
    """Reverse operation - set company to null"""
    Product = apps.get_model('central', 'Product')
    Product.objects.all().update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        (
            "central",
            "0003_product_company_product_is_active_alter_product_name_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            assign_default_company,
            reverse_assign_default_company,
        ),
    ]
