# Generated by Django 5.2.7 on 2026-01-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0004_auto_20260119_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="central.company",
            ),
        ),
    ]
