# Generated by Django 5.2.7 on 2026-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0005_alter_product_company"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["status"], name="company_status_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "is_active"], name="product_company_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="product_category_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="product_sku_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["company", "status"], name="warehouse_company_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["wh_type"], name="warehouse_type_idx"),
        ),
    ]
