# Generated by Django 5.2.7 on 2026-03-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shelf_life_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="storage_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ambient", "Ambient"),
                    ("refrigerated", "Refrigerated"),
                    ("frozen", "Frozen"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="storage_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
