# Generated by Django 5.2.7 on 2026-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0007_product_shelf_life_days_product_storage_conditions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("raw_material", "Raw Material"),
                    ("consumable", "Consumable"),
                    ("finished_good", "Finished Good"),
                    ("semi_finished", "Semi-Finished"),
                    ("packaging", "Packaging"),
                    ("spare_part", "Spare Part"),
                    ("byproduct", "By-Product"),
                    ("waste", "Waste"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
