# Generated by Django 5.2.7 on 2026-01-19 16:29

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.CharField(
                default=apps.inventory.models.Batch.generate_batch_number,
                max_length=100,
                unique=True,
            ),
        ),
    ]
