# Generated by Django 5.2.7 on 2026-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_batch_batch_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="status",
            field=models.CharField(
                choices=[
                    ("EMPTY", "Empty"),
                    ("ALMOST_OUT", "Almost Out"),
                    ("GOOD", "Good"),
                    ("FULL", "Full"),
                ],
                default="EMPTY",
                max_length=20,
            ),
        ),
    ]
