# Generated by Django 5.2.7 on 2026-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
        ("inventory", "0003_stock_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["warehouse", "expiry_date"], name="batch_warehouse_expiry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["product", "expiry_date"], name="batch_product_expiry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["batch_number"], name="batch_number_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["warehouse", "status"], name="stock_warehouse_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["product", "quantity_on_hand"], name="stock_product_qty_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["last_updated"], name="stock_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["batch", "created_at"], name="movement_batch_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "created_at"], name="movement_type_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["reference_number"], name="movement_ref_idx"),
        ),
    ]
