# Generated by Django 5.2.7 on 2026-01-22 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
        ("inventory", "0004_batch_batch_warehouse_expiry_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_reorder_policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reorder_point_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "reorder_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                (
                    "safety_stock_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reorder_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_policies",
                        to="central.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_reorder_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_policies",
                        to="central.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Reorder Policy",
                "verbose_name_plural": "Product Reorder Policies",
            },
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LOW_STOCK", "Low Stock"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                            ("EXPIRY", "Expiry Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=50,
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("STOCK_MOVEMENT", "Stock Movement"),
                            ("SCHEDULED_CHECK", "Scheduled Check"),
                        ],
                        max_length=50,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_inventory_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="central.product",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_inventory_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="central.warehouse",
                    ),
                ),
                (
                    "reorder_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inventory_alerts",
                        to="inventory.product_reorder_policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Alert",
                "verbose_name_plural": "Inventory Alerts",
            },
        ),
        migrations.AddIndex(
            model_name="product_reorder_policy",
            index=models.Index(
                fields=["warehouse", "is_active"], name="reorder_warehouse_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product_reorder_policy",
            index=models.Index(
                fields=["product", "reorder_point_qty"],
                name="reorder_product_point_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product_reorder_policy",
            unique_together={("product", "warehouse")},
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(
                fields=["product", "warehouse"], name="inv_alert_product_resolved_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(fields=["status"], name="inv_alert_status_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(fields=["created_at"], name="inv_alert_created_at_idx"),
        ),
    ]
