# Generated by Django 5.2.7 on 2026-01-22 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
        ("inventory", "0005_product_reorder_policy_inventoryalert_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product_reorder_policy",
            name="reorder_product_point_idx",
        ),
        migrations.RenameField(
            model_name="product_reorder_policy",
            old_name="reorder_point_qty",
            new_name="min_stock_level",
        ),
        migrations.AddIndex(
            model_name="product_reorder_policy",
            index=models.Index(
                fields=["product", "min_stock_level"], name="reorder_product_point_idx"
            ),
        ),
    ]
