# Generated by Django 5.2.7 on 2026-01-22 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
        (
            "inventory",
            "0006_remove_product_reorder_policy_reorder_product_point_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product_reorder_policy",
            new_name="ProductReorderPolicy",
        ),
    ]
