# Generated by Django 5.2.7 on 2026-01-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_rename_product_reorder_policy_productreorderpolicy"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventoryalert",
            new_name="inv_alert_product_whouse_idx",
            old_name="inv_alert_product_resolved_idx",
        ),
    ]
