# Generated by Django 5.2.7 on 2026-01-23 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
        (
            "inventory",
            "0008_rename_inv_alert_product_resolved_idx_inv_alert_product_whouse_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "reorder_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                (
                    "safety_stock_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "retrieval_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In First Out"),
                            ("LIFO", "Last In First Out"),
                            ("FEFO", "First Expired First Out"),
                        ],
                        default="FIFO",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Reorder Policy",
                "verbose_name_plural": "Product Reorder Policies",
            },
        ),
        migrations.CreateModel(
            name="StockMovementBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="productreorderpolicy",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productreorderpolicy",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="productreorderpolicy",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productreorderpolicy",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="productreorderpolicy",
            name="warehouse",
        ),
        migrations.RemoveIndex(
            model_name="stockmovement",
            name="movement_batch_date_idx",
        ),
        migrations.RenameField(
            model_name="stockmovement",
            old_name="quantity",
            new_name="total_quantity",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="batch",
        ),
        migrations.AddField(
            model_name="productpolicy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reorder_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productpolicy",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reorder_policies",
                to="central.product",
            ),
        ),
        migrations.AddField(
            model_name="productpolicy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_reorder_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productpolicy",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reorder_policies",
                to="central.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryalert",
            name="reorder_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="inventory_alerts",
                to="inventory.productpolicy",
            ),
        ),
        migrations.AddField(
            model_name="stockmovementbatch",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.batch"
            ),
        ),
        migrations.AddField(
            model_name="stockmovementbatch",
            name="stock_movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="batches",
            field=models.ManyToManyField(
                related_name="movements",
                through="inventory.StockMovementBatch",
                to="inventory.batch",
            ),
        ),
        migrations.AddIndex(
            model_name="productpolicy",
            index=models.Index(
                fields=["warehouse", "is_active"], name="reorder_warehouse_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpolicy",
            index=models.Index(
                fields=["product", "min_stock_level"], name="reorder_product_point_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productpolicy",
            unique_together={("product", "warehouse")},
        ),
        migrations.DeleteModel(
            name="ProductReorderPolicy",
        ),
        migrations.AlterUniqueTogether(
            name="stockmovementbatch",
            unique_together={("stock_movement", "batch")},
        ),
    ]
