# Generated by Django 5.2.7 on 2026-01-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_productpolicy_stockmovementbatch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryalert",
            name="reorder_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_alerts",
                to="inventory.productpolicy",
            ),
        ),
    ]
