# Generated by Django 5.2.7 on 2026-01-23 14:58

from django.db import migrations


def cleanup_orphaned_alerts(apps, schema_editor):
    """Remove inventory alerts with invalid reorder_policy references"""
    InventoryAlert = apps.get_model('inventory', 'InventoryAlert')
    ProductPolicy = apps.get_model('inventory', 'ProductPolicy')
    
    # Get all valid policy IDs
    valid_policy_ids = set(ProductPolicy.objects.values_list('id', flat=True))
    
    # Delete alerts with invalid policy references
    InventoryAlert.objects.exclude(
        reorder_policy_id__in=valid_policy_ids
    ).exclude(
        reorder_policy_id__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_inventoryalert_reorder_policy"),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_alerts, migrations.RunPython.noop),
    ]
