# Generated by Django 5.2.7 on 2026-01-29 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
        ("inventory", "0011_auto_20260123_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="central.warehouse",
            ),
        ),
    ]
