# Generated by Django 5.2.7 on 2026-01-31 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
        ("inventory", "0013_alter_stockmovement_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="central.warehouse",
            ),
        ),
    ]
