# Generated by Django 5.2.7 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_stockmovement_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="rework_consumed",
            field=models.BooleanField(default=False),
        ),
    ]
