# Generated by Django 5.2.7 on 2026-03-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productionorder",
            old_name="scheduled_end_date",
            new_name="scheduled_end",
        ),
        migrations.RenameField(
            model_name="productionorder",
            old_name="scheduled_start_date",
            new_name="scheduled_start",
        ),
    ]
