# Generated by Django 5.2.7 on 2026-03-26 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0007_product_shelf_life_days_product_storage_conditions_and_more"),
        ("inventory", "0014_alter_stockmovement_warehouse"),
        (
            "production",
            "0002_rename_scheduled_end_date_productionorder_scheduled_end_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReworkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_requested", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="central.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="central.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReworkInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_used", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.batch",
                    ),
                ),
                (
                    "rework_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="production.reworkorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReworkOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_produced", models.FloatField()),
                (
                    "output_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.batch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="central.product",
                    ),
                ),
                (
                    "rework_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="production.reworkorder",
                    ),
                ),
            ],
        ),
    ]
