# Generated by Django 5.2.7 on 2026-03-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("production", "0003_rework_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="planned_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_order",
                to="orders.plannedorder",
            ),
        ),
    ]
