"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import logging

logger = logging.getLogger(__name__)
from corsheaders.defaults import default_headers, default_methods
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "your-default-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

# Add this fallback for production
if not DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]  # Temporary - replace with your actual domain


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #! Third-party apps
    "corsheaders",
    "rest_framework",
    "drf_yasg",
    "rest_framework_simplejwt.token_blacklist",
    "silk",
    "drf_spectacular",
    "django_filters",
    # "django_celery_beat",
    # "django_extensions",
    "djoser",
    #! Local apps
    "apps.accounts",
    "apps.accounting",
    "apps.inventory",
    "apps.formulation",
    "apps.orders",
    "apps.production",
    "apps.purchasing",
    "apps.costing",
    "apps.sales",
    "apps.finance",
    "apps.mail",
    "apps.dashboard",
    "central",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "silk.middleware.SilkyMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if we're on Render (production) or have a DATABASE_URL
render_external_db_url = os.environ.get("RENDER_DB_URL") or os.environ.get(
    "DATABASE_URL"
)

if render_external_db_url:
    # Production: Use the external database URL (Render, Aiven, etc.)
    try:
        import dj_database_url

        if DEBUG:
            DATABASES = {
                "default": {
                    "ENGINE": "django.db.backends.postgresql",
                    "NAME": os.environ.get("POSTGRES_DB"),
                    "USER": os.environ.get("POSTGRES_USER"),
                    "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
                    "HOST": os.environ.get("POSTGRES_HOST"),
                    "PORT": os.environ.get("POSTGRES_PORT"),
                }
            }
        else:
            DATABASES = {"default": dj_database_url.parse(render_external_db_url)}

    except Exception as e:
        logger.error(f"Error configuring database: {e}")
        # Fallback to sqlite for build-time commands
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
else:
    # Local development: Use PostgreSQL with individual env vars
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "mydb"),
            "USER": os.environ.get("POSTGRES_USER", "myuser"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "mypassword"),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Define timezone
CELERY_TIMEZONE = "Africa/Harare"

# Accept JSON task serialization
CELERY_TASK_SERIALIZER = "json"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SIMPLE_JWT = {
    # TODO: adjust token lifetimes when pushing to production
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "BakeryERP API",
    "DESCRIPTION": """
BakeryERP is a modular, warehouse-aware Enterprise Resource Planning system designed for 
multi-warehouse bakery manufacturing operations. It provides a unified backend for managing 
the full operational lifecycle; from raw material procurement through production execution 
to sales fulfillment; with strict inventory traceability and auditable financial integration.

## Core Modules

- **Inventory** : Stock movement-driven ledger with batch tracking, multi-warehouse balances, and full audit trail
- **Formulation** : Versioned recipe management with structured formula lines (materials, instructions, byproducts)
- **Production** : Order-based production execution with batch snapshots, material consumption, and output recording
- **Purchasing** : Supplier and procurement lifecycle management including requisitions, purchase orders, goods receipts, and supplier invoices
- **Costing** : Standard costing, actual cost capture, overhead absorption, variance analysis, and pricing rules
- **Sales & Distribution** : Customer order management and fulfillment workflows

## Design Principles

- **Stock movements are the single source of truth** : inventory balances are always derived from movement records and never manually overridden
- **Formula revisions are immutable snapshots** : production batches capture the formula at execution time, preserving historical accuracy
- **Strict module boundaries** : each module owns its domain; cross-module interaction occurs only through well-defined service interfaces
- **Warehouse-aware throughout** : every operational event is anchored to a physical warehouse

## Authentication
All endpoints require token-based authentication unless otherwise noted.
""",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         },
#     }
# }

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React
    "http://127.0.0.1:3000",
    "http://localhost:8080",  # Vue or Flutter web
    "https://bakeryerpbackend.onrender.com",
    # "https://council-portal.onrender.com",
]

# Optional but helpful:
CORS_ALLOW_HEADERS = list(default_headers) + [
    "content-type",
    "accept",
]
CORS_ALLOW_METHODS = list(default_methods) + ["POST", "OPTIONS"]
CORS_ALLOW_ALL_ORIGINS = True  # Or use CORS_ALLOWED_ORIGINS with exact domains
CORS_ALLOW_CREDENTIALS = True


MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

APPEND_SLASH = False

# Static files for production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": os.environ.get("REDIS_URL", "redis://localhost:6379/1"),
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "TIMEOUT": 60 * 60 * 24,  # Cache timeout in seconds (1 day)
#         },
#     },
# }

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{asctime}:{levelname} {module}.py (line {lineno:d}). {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#             "level": os.getenv("DJANGO_LOG_LEVEL"),
#             "formatter": "simple",
#         },
#         "file": {
#             "class": "logging.FileHandler",
#             "filename": os.getenv("DJANGO_LOG_FILE"),
#             "formatter": "verbose",
#             "level": os.getenv("DJANGO_LOG_LEVEL"),
#         },
#     },
#     "loggers": {
#         "": {
#             "level": os.getenv("DJANGO_LOG_LEVEL"),
#             "handlers": ["file", "console"],
#         }
#     },
#     "root": {
#         "handlers": ["console"],
#         "level": "INFO",
#     },
# }
