# Generated by Django 5.2.7 on 2026-04-28 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("central", "0007_product_shelf_life_days_product_storage_conditions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-entry_date", "-created_at"],
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="journalentryline",
            options={
                "verbose_name": "Journal Entry Line",
                "verbose_name_plural": "Journal Entry Lines",
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("automated", "Automated"),
                    ("manual", "Manual"),
                    ("reversal", "Reversal"),
                ],
                default="automated",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_balanced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_reversed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reference_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reference_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reverses",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="type",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")],
                default="debit",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="source_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="source_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ChartOfAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account_subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("current_asset", "Current Asset"),
                            ("fixed_asset", "Fixed Asset"),
                            ("current_liability", "Current Liability"),
                            ("long_term_liability", "Long-Term Liability"),
                            ("equity", "Equity"),
                            ("operating_revenue", "Operating Revenue"),
                            ("cost_of_sales", "Cost of Sales"),
                            ("operating_expense", "Operating Expense"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6
                    ),
                ),
                (
                    "system_key",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("is_system_account", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_of_accounts",
                        to="central.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chart of Accounts",
                "verbose_name_plural": "Chart of Accounts",
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_fiscal_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_periods",
                        to="central.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Period",
                "verbose_name_plural": "Fiscal Periods",
                "ordering": ["period_start"],
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="fiscal_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="accounting.fiscalperiod",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["company", "entry_date"], name="je_company_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["reference_type", "reference_id"], name="je_ref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["fiscal_period"], name="je_period_idx"),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["company", "account_type"], name="coa_company_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["company", "is_active"], name="coa_company_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chartofaccounts",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["company", "status"], name="fp_company_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["company", "period_start"], name="fp_company_start_idx"
            ),
        ),
    ]
