# Generated by Django 5.2.7 on 2026-05-12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_journalentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("savings", "Savings"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coa_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="accounting.chartofaccounts",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="central.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["company", "is_active"],
                name="ba_company_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["company", "currency"],
                name="ba_company_currency_idx",
            ),
        ),
    ]
