# Generated by Django 5.2.7 on 2026-05-19 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget_key", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField()),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "width",
                    models.CharField(
                        choices=[("half", "Half"), ("full", "Full")],
                        default="half",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("user", "widget_key")},
            },
        ),
    ]
