$kind: http-request
name: Get all batches
url: "{{baseurl}}/inventory/batches?warehouse_id={{wh_1_pie_kings}}&page=2"
method: GET
queryParams:
  warehouse_id: "{{wh_1_pie_kings}}"
  page: "2"
body:
  type: json
  content: "{\r

    \       \"warehouse_id\": \"{{\"\r

    }"
order: 1000
