# Generated by Django 5.2.7 on 2026-03-27 00:00

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("central", "0007_product_shelf_life_days_product_storage_conditions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("need_by", models.DateTimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority_override_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "priority_override_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("priority_override_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority_override_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_planned_order_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="central.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="central.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["need_by", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="plannedorder",
            index=models.Index(
                fields=["status", "need_by"], name="planned_status_need_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannedorder",
            index=models.Index(
                fields=["warehouse", "need_by"], name="planned_wh_need_idx"
            ),
        ),
    ]
