# Generated by Django 5.2.7 on 2026-03-18 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("central", "0006_company_company_status_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.IntegerField()),
                ("batch_size", models.FloatField()),
                ("yield_percentage", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="central.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("INSTRUCTION", "Instruction"),
                            ("MATERIAL", "Material"),
                            ("BYPRODUCT", "Byproduct"),
                            ("PROCESS", "Process"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.FloatField()),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="formulation.formula",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="central.product",
                    ),
                ),
            ],
        ),
    ]
