# Generated by Django 5.2.7 on 2026-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="revision",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="formulaline",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formulaline",
            name="sequence",
            field=models.PositiveIntegerField(),
        ),
    ]
