# Generated by Django 5.2.7 on 2026-03-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulation",
            "0002_alter_formula_revision_alter_formulaline_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="name",
            field=models.CharField(default="sausage roll normal", max_length=255),
            preserve_default=False,
        ),
    ]
