# Generated by Django 5.2.7 on 2026-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0003_formula_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formula',
            name='on_hold_reason',
            field=models.TextField(blank=True),
        ),
    ]
