# Generated by Django 5.2.7 on 2026-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulation", "0004_formula_is_active_formula_on_hold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("deactivated", "Deactivated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
