# Generated by Django 5.2.7 on 2026-04-28 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_alter_journalentry_options_and_more"),
        ("purchasing", "0011_remove_supplier_contact_person"),
        ("sales", "0003_alter_salesorderline_subtotal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountsPayable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_outstanding",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ap_records",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts_payable",
                        to="purchasing.supplier",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ap_record",
                        to="purchasing.supplierinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounts Payable",
                "verbose_name_plural": "Accounts Payable",
            },
        ),
        migrations.CreateModel(
            name="AccountsReceivable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_outstanding",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts_receivable",
                        to="sales.customer",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_record",
                        to="sales.invoice",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_records",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounts Receivable",
                "verbose_name_plural": "Accounts Receivable",
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accounts_payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.accountspayable",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_payments",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment",
                "verbose_name_plural": "Supplier Payments",
            },
        ),
        migrations.AddIndex(
            model_name="accountspayable",
            index=models.Index(
                fields=["supplier", "status"], name="ap_supplier_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountspayable",
            index=models.Index(
                fields=["due_date", "status"], name="ap_due_date_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountsreceivable",
            index=models.Index(
                fields=["customer", "status"], name="ar_customer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountsreceivable",
            index=models.Index(
                fields=["due_date", "status"], name="ar_due_date_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["accounts_payable", "payment_date"], name="sp_ap_date_idx"
            ),
        ),
    ]
