# Generated by Django 5.2.7 on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_bankaccount"),
        ("finance", "0002_customerpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_payments",
                to="accounting.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="accounting.bankaccount",
            ),
        ),
    ]
