# Generated by Django 5.2.7 on 2026-04-24 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("central", "0007_product_shelf_life_days_product_storage_conditions_and_more"),
        ("formulation", "0005_alter_formula_status"),
        ("production", "0004_productionorder_planned_order"),
        ("purchasing", "0011_remove_supplier_contact_person"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostingEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_material_cost",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("overhead_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "actual_output_quantity",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "actual_waste_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("cost_per_unit", models.DecimalField(decimal_places=6, max_digits=14)),
                ("computed_at", models.DateTimeField()),
                ("currency", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costing_entries",
                        to="central.product",
                    ),
                ),
                (
                    "production_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costing_entry",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costing_entries",
                        to="central.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costing Entry",
                "verbose_name_plural": "Costing Entries",
            },
        ),
        migrations.CreateModel(
            name="CostingEntryLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actual_quantity_used",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "unit_price_used",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("actual_cost", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "batch_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costing_entry_lines",
                        to="production.batchmaterial",
                    ),
                ),
                (
                    "costing_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="costing.costingentry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costing_entry_lines",
                        to="central.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costing Entry Line",
                "verbose_name_plural": "Costing Entry Lines",
            },
        ),
        migrations.CreateModel(
            name="OverheadRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_overhead_budgeted",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "planned_production_units",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("rate_per_unit", models.DecimalField(decimal_places=6, max_digits=14)),
                ("currency", models.CharField(max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overhead_rates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overhead_rates",
                        to="central.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Rate",
                "verbose_name_plural": "Overhead Rates",
            },
        ),
        migrations.AddField(
            model_name="costingentry",
            name="overhead_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costing_entries",
                to="costing.overheadrate",
            ),
        ),
        migrations.CreateModel(
            name="StandardCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "material_cost_per_unit",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "overhead_cost_per_unit",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "total_standard_cost_per_unit",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "batch_size_used",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "yield_percentage_used",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                ("computed_at", models.DateTimeField()),
                ("currency", models.CharField(max_length=10)),
                (
                    "computed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_costs_computed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_costs",
                        to="formulation.formula",
                    ),
                ),
                (
                    "overhead_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_costs",
                        to="costing.overheadrate",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_costs",
                        to="central.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Cost",
                "verbose_name_plural": "Standard Costs",
            },
        ),
        migrations.CreateModel(
            name="ProductPricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_gross_margin_percentage",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "minimum_margin_percentage",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "recommended_selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "minimum_selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_rule",
                        to="central.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_rules_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard_cost_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_rules",
                        to="costing.standardcost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Pricing Rule",
                "verbose_name_plural": "Product Pricing Rules",
            },
        ),
        migrations.CreateModel(
            name="CostVarianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "material_price_variance",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "material_usage_variance",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "yield_variance",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "overhead_variance",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "total_variance",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(decimal_places=4, max_digits=9),
                ),
                ("is_favourable", models.BooleanField()),
                ("computed_at", models.DateTimeField()),
                (
                    "costing_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variance_record",
                        to="costing.costingentry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variance_records",
                        to="central.product",
                    ),
                ),
                (
                    "production_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variance_records",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variance_records",
                        to="central.warehouse",
                    ),
                ),
                (
                    "standard_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variance_records",
                        to="costing.standardcost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Variance Record",
                "verbose_name_plural": "Cost Variance Records",
            },
        ),
        migrations.AddField(
            model_name="costingentry",
            name="standard_cost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costing_entries",
                to="costing.standardcost",
            ),
        ),
        migrations.CreateModel(
            name="StandardCostLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_per_batch",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "quantity_per_unit",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "unit_price_used",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("cost_per_unit", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "cost_percentage",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "formula_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_cost_lines",
                        to="formulation.formulaline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_cost_lines",
                        to="central.product",
                    ),
                ),
                (
                    "standard_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="costing.standardcost",
                    ),
                ),
                (
                    "supplier_product_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standard_cost_lines",
                        to="purchasing.supplierproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Cost Line",
                "verbose_name_plural": "Standard Cost Lines",
                "ordering": ["-cost_percentage"],
            },
        ),
        migrations.AddIndex(
            model_name="overheadrate",
            index=models.Index(
                fields=["warehouse", "period_start", "period_end"],
                name="overhead_wh_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="standardcost",
            index=models.Index(
                fields=["product", "computed_at"], name="stdcost_product_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standardcost",
            index=models.Index(fields=["formula"], name="stdcost_formula_idx"),
        ),
        migrations.AddIndex(
            model_name="costvariancerecord",
            index=models.Index(
                fields=["product", "computed_at"], name="variance_product_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costvariancerecord",
            index=models.Index(
                fields=["warehouse", "is_favourable"], name="variance_wh_favourable_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costingentry",
            index=models.Index(
                fields=["product", "computed_at"], name="costentry_product_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costingentry",
            index=models.Index(
                fields=["warehouse", "computed_at"], name="costentry_wh_date_idx"
            ),
        ),
    ]
