# Generated by Django 5.2.7 on 2026-01-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("warehouse_staff", "Warehouse Staff"),
                    ("production_operator", "Production Operator"),
                    ("production_supervisor", "Production Supervisor"),
                    ("inventory_controller", "Inventory Controller"),
                    ("planner", "Planner"),
                    ("sales_rep", "Sales Rep"),
                    ("purchasing_officer", "Purchasing Officer"),
                    ("accountant", "Accountant"),
                    ("quality_officer", "Quality Officer"),
                    ("manager", "Manager"),
                    ("owner_director", "Owner / Director"),
                    ("system_admin", "System Admin"),
                ],
                default="owner_director",
                max_length=30,
            ),
        ),
    ]
