# Generated by Django 5.2.7 on 2026-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_department_user_role"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("warehouse_staff", "Warehouse Staff"),
                    ("production_operator", "Production Operator"),
                    ("production_supervisor", "Production Supervisor"),
                    ("inventory_controller", "Inventory Controller"),
                    ("planner", "Planner"),
                    ("sales_rep", "Sales Rep"),
                    ("purchasing_officer", "Purchasing Officer"),
                    ("accountant", "Accountant"),
                    ("quality_officer", "Quality Officer"),
                    ("manager", "Manager"),
                    ("owner_director", "Owner / Director"),
                    ("system_admin", "System Admin"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="user_role_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["emp_code"], name="user_emp_code_idx"),
        ),
    ]
