# Generated by Django 5.2.7 on 2026-01-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role_user_user_role_idx_and_more"),
        ("central", "0006_company_company_status_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="central.company",
            ),
        ),
    ]
