# Generated by Django 5.2.7 on 2026-04-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptlineitem",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptlineitem",
            name="manufacturing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptlineitem",
            name="supplier_batch_ref",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
