# Generated by Django 5.2.7 on 2026-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_purchaseorder_audit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="quantity_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
