# Generated by Django 5.2.7 on 2026-04-01 13:48

from django.conf import settings
from django.db import migrations, models


auth_user = settings.AUTH_USER_MODEL


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0004_goodsreceipt_rejection_reason_and_more"),
        migrations.swappable_dependency(auth_user),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisition",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="purchase_requisitions",
                to="central.warehouse",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="submitted_purchase_requisitions",
                to=auth_user,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="approved_purchase_requisitions",
                to=auth_user,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="rejected_purchase_requisitions",
                to=auth_user,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="converted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Converted", "Converted"),
                ],
                default="Draft",
                max_length=50,
            ),
        ),
    ]
