# Generated by Django 5.2.7 on 2026-04-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0007_product_shelf_life_days_product_storage_conditions_and_more"),
        ("purchasing", "0006_goodsreceiptlineitem_unit_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="central.company",
            ),
            preserve_default=False,
        ),
    ]
