# Generated by Django 5.2.7 on 2026-05-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_remove_supplier_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Supplier's catalogue/quoted price (auto-filled from SupplierProduct).", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier providing this specific line item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_line_items', to='purchasing.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional primary/default supplier for this PO. Each line item carries its own supplier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchasing.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Agreed price for this order (may differ from quoted price due to discounts, etc.).', max_digits=10),
        ),
    ]
