# Widget registry — one entry per infolet.
# endpoint: the backend URL the frontend calls to fetch data for this widget.
# dataPath:  dot-notation key inside that response to extract (null = use full response).
# width:     default grid width — frontend may override via saved layout.

WIDGET_REGISTRY = {
    # ── Production ──────────────────────────────────────────────────────────
    "production_wip": {
        "label": "WIP Orders",
        "description": "Number of production orders currently in progress.",
        "module": "Production",
        "endpoint": "/production/overview/summary",
        "dataPath": "wip_order_count",
        "width": "half",
    },
    "production_orders_status": {
        "label": "Production Order Status",
        "description": "Breakdown of production orders by status.",
        "module": "Production",
        "endpoint": "/production/overview/summary",
        "dataPath": "production_order_counts_by_status",
        "width": "half",
    },
    "production_waste": {
        "label": "Waste & Yield",
        "description": "Waste quantity and waste rate for the current period.",
        "module": "Production",
        "endpoint": "/production/overview/summary",
        "dataPath": "waste",
        "width": "half",
    },
    "production_output": {
        "label": "Output vs Target",
        "description": "Expected output compared to actual completed quantity.",
        "module": "Production",
        "endpoint": "/production/overview/summary",
        "dataPath": "expected_vs_actual_output",
        "width": "half",
    },
    "production_top_products": {
        "label": "Top Products Produced",
        "description": "Top products by production volume this period.",
        "module": "Production",
        "endpoint": "/production/overview/summary",
        "dataPath": "top_products_produced",
        "width": "full",
    },
    "production_yield_trends": {
        "label": "Yield Trends",
        "description": "Yield percentage trends over time.",
        "module": "Production",
        "endpoint": "/production/overview/yield-trends",
        "dataPath": None,
        "width": "full",
    },
    "production_schedule": {
        "label": "Schedule Adherence",
        "description": "How closely production is tracking the schedule.",
        "module": "Production",
        "endpoint": "/production/overview/schedule-adherence",
        "dataPath": None,
        "width": "half",
    },
    # ── Inventory ────────────────────────────────────────────────────────────
    "inventory_stock_status": {
        "label": "Stock Status",
        "description": "Distribution of stock levels: Full, Good, Almost Out, Empty.",
        "module": "Inventory",
        "endpoint": "/inventory/overview/summary",
        "dataPath": "stock_status_counts",
        "width": "half",
    },
    "inventory_low_stock": {
        "label": "Low Stock Alerts",
        "description": "Top products with critically low stock levels.",
        "module": "Inventory",
        "endpoint": "/inventory/overview/summary",
        "dataPath": "top_low_stock_products",
        "width": "full",
    },
    "inventory_expiring": {
        "label": "Expiring Batches",
        "description": "Batches expiring within 7, 14, and 30 days.",
        "module": "Inventory",
        "endpoint": "/inventory/overview/summary",
        "dataPath": "batches_expiring",
        "width": "half",
    },
    "inventory_expired": {
        "label": "Expired Inventory",
        "description": "Expired batch count and total quantity to write off.",
        "module": "Inventory",
        "endpoint": "/inventory/overview/summary",
        "dataPath": "expired_batches_with_quantity",
        "width": "half",
    },
    "inventory_alerts": {
        "label": "Inventory Alerts",
        "description": "Open inventory alerts grouped by type.",
        "module": "Inventory",
        "endpoint": "/inventory/overview/summary",
        "dataPath": "open_alert_counts_by_type",
        "width": "half",
    },
    "inventory_movement": {
        "label": "Stock Movement Trends",
        "description": "Stock in/out movement trends over time.",
        "module": "Inventory",
        "endpoint": "/inventory/overview/movement-trends",
        "dataPath": None,
        "width": "full",
    },
    # ── Purchasing ───────────────────────────────────────────────────────────
    "po_status": {
        "label": "Purchase Order Status",
        "description": "PO counts broken down by status.",
        "module": "Purchasing",
        "endpoint": "/purchasing/overview/summary",
        "dataPath": "po_counts_by_status",
        "width": "half",
    },
    "open_po_value": {
        "label": "Open PO Value",
        "description": "Total monetary value of open purchase orders.",
        "module": "Purchasing",
        "endpoint": "/purchasing/overview/summary",
        "dataPath": "open_po_value",
        "width": "half",
    },
    "overdue_pos": {
        "label": "Overdue Purchase Orders",
        "description": "Count and value of overdue POs.",
        "module": "Purchasing",
        "endpoint": "/purchasing/overview/summary",
        "dataPath": "overdue_pos",
        "width": "half",
    },
    "pending_approvals": {
        "label": "Pending Approvals",
        "description": "Items awaiting approval: PRs, POs, GRNs, supplier invoices.",
        "module": "Purchasing",
        "endpoint": "/purchasing/overview/summary",
        "dataPath": "pending_approvals",
        "width": "half",
    },
    "supplier_risk": {
        "label": "Supplier Health",
        "description": "Suppliers on hold, inactive suppliers, and expired documents.",
        "module": "Purchasing",
        "endpoint": "/purchasing/overview/summary",
        "dataPath": "supplier_risk",
        "width": "half",
    },
    "purchasing_trends": {
        "label": "Purchasing Trends",
        "description": "Purchase volume and spend trends over time.",
        "module": "Purchasing",
        "endpoint": "/purchasing/overview/trends",
        "dataPath": None,
        "width": "full",
    },
    # ── Sales ────────────────────────────────────────────────────────────────
    "sales_revenue": {
        "label": "Daily Revenue",
        "description": "Total sales revenue for today.",
        "module": "Sales",
        "endpoint": "/sales/reports/daily-summary",
        "dataPath": "total_revenue",
        "width": "half",
    },
    "sales_gross_profit": {
        "label": "Daily Gross Profit",
        "description": "Gross profit (revenue minus COGS) for today.",
        "module": "Sales",
        "endpoint": "/sales/reports/daily-summary",
        "dataPath": "gross_profit",
        "width": "half",
    },
    "sales_transactions": {
        "label": "Transactions Today",
        "description": "Number of sales transactions recorded today.",
        "module": "Sales",
        "endpoint": "/sales/reports/daily-summary",
        "dataPath": "total_transactions",
        "width": "half",
    },
    "sales_cogs": {
        "label": "Daily COGS",
        "description": "Cost of goods sold today.",
        "module": "Sales",
        "endpoint": "/sales/reports/daily-summary",
        "dataPath": "total_cogs",
        "width": "half",
    },
    # ── Costing ──────────────────────────────────────────────────────────────
    "cost_variance_summary": {
        "label": "Cost Variance Summary",
        "description": "Aggregate variance across all products and batches.",
        "module": "Costing",
        "endpoint": "/costing/reports/variance-analysis",
        "dataPath": None,
        "width": "full",
    },
    "adverse_variances": {
        "label": "Adverse Variances",
        "description": "Count of batches with unfavourable cost variances.",
        "module": "Costing",
        "endpoint": "/costing/reports/variance-analysis",
        "dataPath": None,
        "width": "half",
    },
    "costing_margin": {
        "label": "Product Margins",
        "description": "Margin report across products.",
        "module": "Costing",
        "endpoint": "/costing/reports/margin-report",
        "dataPath": None,
        "width": "full",
    },
    # ── Finance ──────────────────────────────────────────────────────────────
    "finance_net_profit": {
        "label": "Net Profit",
        "description": "Net profit/loss for the current period.",
        "module": "Finance",
        "endpoint": "/finance/reports/income-statement",
        "dataPath": "net_profit",
        "width": "half",
    },
    "finance_gross_profit": {
        "label": "Gross Profit",
        "description": "Gross profit for the current period.",
        "module": "Finance",
        "endpoint": "/finance/reports/income-statement",
        "dataPath": "gross_profit",
        "width": "half",
    },
    "finance_revenue": {
        "label": "Total Revenue",
        "description": "Total revenue for the current period.",
        "module": "Finance",
        "endpoint": "/finance/reports/income-statement",
        "dataPath": "total_revenue",
        "width": "half",
    },
    "finance_expenses": {
        "label": "Operating Expenses",
        "description": "Total operating expenses for the current period.",
        "module": "Finance",
        "endpoint": "/finance/reports/income-statement",
        "dataPath": "total_operating_expenses",
        "width": "half",
    },
    "finance_pnl": {
        "label": "P&L Summary",
        "description": "Full profit and loss statement for the current period.",
        "module": "Finance",
        "endpoint": "/finance/reports/income-statement",
        "dataPath": None,
        "width": "full",
    },
}

# Default layout shown to new users (first 8 widgets, one per key area)
DEFAULT_LAYOUT = [
    {"widget_key": "production_wip",       "position": 0, "is_visible": True, "width": "half"},
    {"widget_key": "production_waste",     "position": 1, "is_visible": True, "width": "half"},
    {"widget_key": "inventory_stock_status","position": 2, "is_visible": True, "width": "half"},
    {"widget_key": "inventory_low_stock",  "position": 3, "is_visible": True, "width": "full"},
    {"widget_key": "pending_approvals",    "position": 4, "is_visible": True, "width": "half"},
    {"widget_key": "sales_revenue",        "position": 5, "is_visible": True, "width": "half"},
    {"widget_key": "finance_net_profit",   "position": 6, "is_visible": True, "width": "half"},
    {"widget_key": "cost_variance_summary","position": 7, "is_visible": True, "width": "full"},
]
