# Generated by Django 5.2.7 on 2026-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_delivery_deliveryline_invoice_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderline",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
